<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2020-2024, Sreeni Viswanadha <sreeni@viswanadha.net>.
Copyright (c) 2024, Marc Mazas <mazas.marc@gmail.com>.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the names of of the copyright holders nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org</groupId>
    <artifactId>javacc</artifactId>
    <version>8.1.0-SNAPSHOT</version>
    <relativePath></relativePath>
  </parent>

  <groupId>org.javacc.generator.cpp</groupId>
  <artifactId>it</artifactId>
  <version>1.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>JavaCC C++ code generator / it</name>

  <profiles>

    <profile>
      <id>Windows</id>
      <activation>
        <os>
          <family>Windows</family>
        </os>
      </activation>
      <properties>
        <suffix>exe</suffix>
        <bigobj>/bigobj</bigobj>
        <std />
        <cliargs>/FS</cliargs>
      </properties>
    </profile>

    <profile>
      <id>Linux</id>
      <activation>
        <os>
          <family>Linux</family>
        </os>
      </activation>
      <properties>
        <suffix>sh</suffix>
        <bigobj />
        <std>-std=c++11</std>
        <cliargs />
      </properties>
    </profile>

    <profile>
      <id>MacOS</id>
      <activation>
        <os>
          <family>mac</family>
        </os>
      </activation>
      <properties>
        <suffix>sh</suffix>
        <bigobj />
        <std>-std=c++11</std>
        <cliargs />
      </properties>
    </profile>

    <profile>
      <id>jcc8</id>
      <activation>
        <file>
          <exists>${basedir}/src/main/javacc</exists>
        </file>
      </activation>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>org.javacc.generator</groupId>
                  <artifactId>cpp</artifactId>
                  <version>${javacc.cpp.version}</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jcc8jcc</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>javacc</goal>
                </goals>
                <configuration>
                  <outputDirectory>${project.basedir}/target/generated-sources/cpp</outputDirectory>
                  <sourceDirectory>${project.basedir}/src/main/javacc</sourceDirectory>
                  <codeGenerator>c++</codeGenerator>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <libraries>
                <library>
                  <type>executable</type>
                  <!-- just compile, link and package, do not run anything-->
                  <!--                  <run>true</run>-->
                </library>
              </libraries>
              <cpp>
                <debug>false</debug>
                <defines>
                  <define>JJ8</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                </includePaths>
                <options>
                  <option>${cliargs}</option>
                  <option>${bigobj}</option>
                  <option>${std}</option>
                </options>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>jjt8</id>
      <activation>
        <file>
          <exists>${basedir}/src/main/jjtree</exists>
        </file>
      </activation>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>org.javacc.generator</groupId>
                  <artifactId>cpp</artifactId>
                  <version>${javacc.cpp.version}</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jjt8jjt</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>jjtree-javacc</goal>
                </goals>
                <configuration>
                  <outputDirectory>${project.basedir}/target/generated-sources/cpp</outputDirectory>
                  <sourceDirectory>${project.basedir}/src/main/jjtree</sourceDirectory>
                  <nodeDirectory>${project.basedir}/src/main/cpp</nodeDirectory>
                  <codeGenerator>c++</codeGenerator>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <libraries>
                <library>
                  <type>executable</type>
                  <run>true</run>
                </library>
              </libraries>
              <cpp>
                <debug>false</debug>
                <defines>
                  <define>JJ8</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/jjtree</path>
                  </includePath>
                </includePaths>
                <options>
                  <option>${cliargs}</option>
                  <option>${bigobj}</option>
                  <option>${std}</option>
                </options>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>jjt8w</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>org.javacc.generator</groupId>
                  <artifactId>cpp</artifactId>
                  <version>${javacc.cpp.version}</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jjt8wjjt</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>jjtree-javacc</goal>
                </goals>
                <configuration>
                  <outputDirectory>${project.basedir}/target/generated-sources/cpp</outputDirectory>
                  <sourceDirectory>${project.basedir}/src/main/jjtree</sourceDirectory>
                  <nodeDirectory>${project.basedir}/src/main/cpp</nodeDirectory>
                  <codeGenerator>c++</codeGenerator>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <libraries>
                <library>
                  <type>executable</type>
                  <run>true</run>
                </library>
              </libraries>
              <cpp>
                <defines>
                  <define>JJ8</define>
                  <define>JAVACC_CHAR_TYPE=wchar_t</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/jjtree</path>
                  </includePath>
                </includePaths>
                <options>
                  <option>${cliargs}</option>
                  <option>${bigobj}</option>
                  <option>${std}</option>
                </options>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>jcc7</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>net.java.dev.javacc</groupId>
                  <artifactId>javacc</artifactId>
                  <version>7.0.6</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jcc7jcc</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>javacc</goal>
                </goals>
                <configuration>
                  <outputDirectory>target/generated-sources/cpp</outputDirectory>
                  <outputLanguage>c++</outputLanguage>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <libraries>
                <library>
                  <type>executable</type>
                  <run>true</run>
                </library>
              </libraries>
              <cpp>
                <defines>
                  <define>JJ7</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                </includePaths>
                <options>
                  <option>${cliargs}</option>
                  <option>${bigobj}</option>
                  <option>${std}</option>
                </options>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>jcc7w</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>net.java.dev.javacc</groupId>
                  <artifactId>javacc</artifactId>
                  <version>7.0.6</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jcc7wjcc</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>javacc</goal>
                </goals>
                <configuration>
                  <outputDirectory>target/generated-sources/cpp</outputDirectory>
                  <outputLanguage>c++</outputLanguage>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <libraries>
                <library>
                  <type>executable</type>
                  <run>true</run>
                </library>
              </libraries>
              <cpp>
                <defines>
                  <define>JJ7</define>
                  <define>WIDE_CHAR</define>
                  <define>JAVACC_CHAR_TYPE=wchar_t</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                </includePaths>
                <options>
                  <option>${cliargs}</option>
                  <option>${bigobj}</option>
                  <option>${std}</option>
                </options>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>jjt7</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>net.java.dev.javacc</groupId>
                  <artifactId>javacc</artifactId>
                  <version>7.0.6</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jjt7jjt</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>jjtree-javacc</goal>
                </goals>
                <configuration>
                  <outputDirectory>target/generated-sources/cpp</outputDirectory>
                  <outputLanguage>c++</outputLanguage>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <libraries>
                <library>
                  <type>executable</type>
                  <run>true</run>
                </library>
              </libraries>
              <cpp>
                <defines>
                  <define>JJ7</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/jjtree</path>
                  </includePath>
                </includePaths>
                <options>
                  <option>${cliargs}</option>
                  <option>${bigobj}</option>
                  <option>${std}</option>
                </options>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <id>jjt7w</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <dependency>
                  <groupId>net.java.dev.javacc</groupId>
                  <artifactId>javacc</artifactId>
                  <version>7.0.6</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jjt7wjjt</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>jjtree-javacc</goal>
                </goals>
                <configuration>
                  <outputDirectory>target/generated-sources/cpp</outputDirectory>
                  <outputLanguage>c++</outputLanguage>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <extensions>true</extensions>
            <configuration>
              <libraries>
                <library>
                  <type>executable</type>
                  <run>true</run>
                </library>
              </libraries>
              <cpp>
                <defines>
                  <define>JJ7</define>
                  <define>WIDE_CHAR</define>
                  <define>JAVACC_CHAR_TYPE=wchar_t</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/jjtree</path>
                  </includePath>
                </includePaths>
                <options>
                  <option>${cliargs}</option>
                  <option>${bigobj}</option>
                  <option>${std}</option>
                </options>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <!-- nar-maven-plugin: to find VS version and home directory: 2024/07
           version 3.10.1:
            for VS up to 2017 reads registry keys, and
            for VS 2019+ reads pom properties, but not environment variables;
             so, in that case, to avoid having to modify properties in the poms:
              set 2 new environment variables VisualStudioVersion (like 17.10) and VisualStudioDir 
              (path up to VC/TOOLS/MSVC/nn.nn.nnnnn/... excluded),
              (use dir /s %windir%\link.exe and dir /s "%programfiles%\link.exe"),
              so this profile will be activated and pick them
           version 3.10.2 tries to read environment variables, but has not been published yet  -->
      <id>nar-visualstudio-env</id>
      <activation>
        <property>
          <name>env.VISUALSTUDIOVERSION</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <configuration>
              <debug>true</debug>
              <commandLogLevel>3</commandLogLevel>
              <windowsMsvcVersion>${env.VISUALSTUDIOVERSION}</windowsMsvcVersion>
              <!--              <windowsMsvcVersion>17.10</windowsMsvcVersion>-->
              <windowsMsvcDir>${env.VISUALSTUDIODIR}</windowsMsvcDir>
              <!--              <windowsMsvcDir>C:/Progra~1/MIB055~1/2022/PROFES~1/</windowsMsvcDir>-->
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <!--  just as a record of a less usable solution for above -->
    <!--  <properties>-->
    <!--    <nar.windows.msvc.version>17.10</nar.windows.msvc.dir>-->
    <!--    <nar.windows.msvc.dir>C:/Progra~1/MIB055~1/2022/PROFES~1/</nar.windows.msvc.dir>-->
    <!--  </properties>-->

  </profiles>
</project>