<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the names of the copyright holders nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org</groupId>
    <artifactId>javacc</artifactId>
    <version>8.1.0</version>
    <relativePath></relativePath>
  </parent>

  <groupId>org.javacc.generator.cpp</groupId>
  <artifactId>it</artifactId>
  <version>1.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>JavaCC C++ code generator / it</name>

  <!-- 
       ment to be called by maven-invoker-plugin from javacc-8-cpp/pom.xml,
       note: parent is javacc-8/pom.xml, not javacc-8-cpp/pom.xml
       defines non herited settings (help, nar) and specific settings (codeGenerator, profiles)
  -->

  <properties>
    <nar-maven-plugin.version>3.10.1</nar-maven-plugin.version>
    <maven-deploy-plugin.version>3.1.3</maven-deploy-plugin.version>
  </properties>

  <build>

    <pluginManagement>
      <plugins>
        <!-- all in parent javacc-8/pom.xml except the following ones -->
        <plugin>
          <!-- processes JavaCC/JJTree grammar files;
               goals: javacc, jjtree-javacc, jjtree -->
          <groupId>org.javacc.plugin</groupId>
          <artifactId>javacc-maven-plugin</artifactId>
          <version>${javacc-maven-plugin.version}</version>
          <dependencies>
            <!-- uses v8 C++ generator; overriden in v7 profiles -->
            <dependency>
              <groupId>org.javacc.generator</groupId>
              <artifactId>cpp</artifactId>
              <version>${javacc.cpp.version}</version>
              <scope>runtime</scope>
            </dependency>
          </dependencies>
        </plugin>
        <plugin>
          <!-- allows to compile C++ code on different architectures with different
               compilers/linkers -->
          <!-- nar lifecycle: see https://maven-nar.github.io/lifecycle.html -->
          <groupId>com.github.maven-nar</groupId>
          <artifactId>nar-maven-plugin</artifactId>
          <version>${nar-maven-plugin.version}</version>
          <extensions>true</extensions>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>

      <plugin>
        <groupId>org.javacc.plugin</groupId>
        <artifactId>javacc-maven-plugin</artifactId>
        <configuration>
          <codeGenerator>c++</codeGenerator>
        </configuration>
      </plugin>

      <plugin>
        <!-- kept as a nar-maven-plugin dependency, to avoid an incompatible version warning -->
        <!-- uploads the project artifacts to the internal remote repository;
             goal: deploy, deploy-file -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>${maven-deploy-plugin.version}</version>
      </plugin>

      <plugin>
        <groupId>com.github.maven-nar</groupId>
        <artifactId>nar-maven-plugin</artifactId>
        <extensions>true</extensions>
        <!-- nar configuration: see https://maven-nar.github.io/configuration.html -->
        <!-- note that this nar plugin does not allow to specify executions, but only one
             "execution" trough the run setting; so for mutiple executions we'll use the
             mavec-exec-plugin (see for example bas01) -->
        <configuration>
          <libraries>
            <library>
              <type>executable</type>
              <!-- just compile, link and package, do not run anything by default; runs will be
                     through the exec-maven-plugin or this nar plugin (with overriden setting) -->
              <run>false</run>
            </library>
          </libraries>
          <cpp>
            <debug>false</debug>
            <includePaths>
              <includePath>
                <path>${project.basedir}/src/main/cpp</path>
              </includePath>
              <includePath>
                <path>${project.basedir}/target/generated-sources/cpp</path>
              </includePath>
            </includePaths>
            <options>
              <!-- defined in the architecture specific profiles -->
              <option>${cliargs}</option>
              <option>${bigobj}</option>
              <option>${std}</option>
            </options>
          </cpp>
        </configuration>
      </plugin>

    </plugins>

  </build>

  <profiles>

    <profile>
      <id>Windows</id>
      <activation>
        <os>
          <family>Windows</family>
        </os>
      </activation>
      <properties>
        <suffix>exe</suffix>
        <bigobj>/bigobj</bigobj>
        <std />
        <cliargs>/FS</cliargs>
      </properties>
    </profile>

    <profile>
      <id>Linux</id>
      <activation>
        <os>
          <family>Linux</family>
        </os>
      </activation>
      <properties>
        <suffix>sh</suffix>
        <bigobj />
        <std>-std=c++11</std>
        <cliargs />
      </properties>
    </profile>

    <profile>
      <id>MacOS</id>
      <activation>
        <os>
          <family>mac</family>
        </os>
      </activation>
      <properties>
        <suffix>sh</suffix>
        <bigobj />
        <std>-std=c++11</std>
        <cliargs />
      </properties>
    </profile>

    <profile>
      <!-- JJTree/JavaCC project compiled with JavaCC v8; implicitely activated -->
      <id>jjt8</id>
      <activation>
        <file>
          <exists>${basedir}/src/main/jjtree</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jjt8-jjt-jjc</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>jjtree-javacc</goal>
                </goals>
                <configuration>
                  <sourceDirectory>src/main/jjtree</sourceDirectory>
                  <interimDirectory>target/generated-sources/jjtree</interimDirectory>
                  <outputDirectory>target/generated-sources/cpp</outputDirectory>
                  <nodeDirectory>src/main/cpp</nodeDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <configuration>
              <cpp>
                <defines>
                  <define>JJ8</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/jjtree</path>
                  </includePath>
                </includePaths>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <!-- JavaCC project compiled with JavaCC v8; implicitely activated -->
      <id>jcc8</id>
      <activation>
        <file>
          <exists>${basedir}/src/main/javacc</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jcc8-jcc</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>javacc</goal>
                </goals>
                <configuration>
                  <sourceDirectory>src/main/javacc</sourceDirectory>
                  <outputDirectory>target/generated-sources/cpp</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <configuration>
              <cpp>
                <defines>
                  <define>JJ8</define>
                </defines>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <!-- JJTree/JavaCC project compiled with JavaCC v7; needs explicit activation -->
      <id>jjt7</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <!-- uses v7; overrides general build setting -->
                <dependency>
                  <groupId>net.java.dev.javacc</groupId>
                  <artifactId>javacc</artifactId>
                  <version>${javacc.v7.version}</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jjt7jjt</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>jjtree-javacc</goal>
                </goals>
                <configuration>
                  <outputLanguage>c++</outputLanguage>
                  <outputDirectory>target/generated-sources/cpp</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <configuration>
              <cpp>
                <defines>
                  <define>JJ7</define>
                </defines>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/jjtree</path>
                  </includePath>
                </includePaths>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <!-- JavaCC project compiled with JavaCC v7; needs explicit activation -->
      <id>jcc7</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>org.javacc.plugin</groupId>
              <artifactId>javacc-maven-plugin</artifactId>
              <version>${javacc-maven-plugin.version}</version>
              <dependencies>
                <!-- uses v7; overrides general build setting -->
                <dependency>
                  <groupId>net.java.dev.javacc</groupId>
                  <artifactId>javacc</artifactId>
                  <version>${javacc.v7.version}</version>
                  <scope>runtime</scope>
                </dependency>
              </dependencies>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>org.javacc.plugin</groupId>
            <artifactId>javacc-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jcc7jcc</id>
                <phase>generate-sources</phase>
                <goals>
                  <goal>javacc</goal>
                </goals>
                <configuration>
                  <outputLanguage>c++</outputLanguage>
                  <outputDirectory>target/generated-sources/cpp</outputDirectory>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <configuration>
              <cpp>
                <defines>
                  <define>JJ7</define>
                </defines>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

    <profile>
      <!-- nar plugin with a Visual Studio environment -->
      <!-- nar-maven-plugin: to find VS version and home directory: 2024/07
           version 3.10.1:
            for VS up to 2017 reads registry keys, and
            for VS 2019+ reads pom properties, but not environment variables;
             so, in that case, to avoid having to modify properties in the poms:
              set 2 new environment variables VisualStudioVersion (like 17.10) and VisualStudioDir 
              (path up to VC/TOOLS/MSVC/nn.nn.nnnnn/... excluded), 
              (use dir /s %windir%\link.exe and dir /s "%programfiles%\link.exe" to find them),
              (unfortunately using the short name form does not seem to avoid warnings D9027 & D9024),
              so this profile will be activated and pick them
           version 3.10.2 tries to read environment variables, but has not been published yet  -->
      <id>nar-visualstudio-env</id>
      <activation>
        <property>
          <name>env.VISUALSTUDIOVERSION</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <version>${nar-maven-plugin.version}</version>
            <extensions>true</extensions>
            <configuration>
              <!-- 0=err; 1=warn; 2= info; 3:verbose; 4=debug -->
              <!-- with 3 use ant debug property to see the command line like -->
              <!-- [DEBUG] "...\cl" /FS /bigobj  /c /nologo /EHsc /DNDEBUG /MD /GR
              /Fd...\target\nar\obj\amd64-Windows-msvc\ 
              /DJJ8 /DWIN32 /DWIN64
              /I...\target\nar\obj\amd64-Windows-msvc 
              /I...\target\nar\obj\amd64-Windows-msvc
              /I...\src\main\cpp 
              /I...\target\generated-sources\cpp 
              /I...\VC\Tools\MSVC\14.41.34120\include
              /I...\Windows Kits\10\Include\10.0.19041.0\shared
              /I...\Windows Kits\10\Include\10.0.19041.0\ucrt 
              /I...\Windows Kits\10\Include\10.0.19041.0\um 
              /I...\Windows Kits\10\Include\10.0.19041.0\winrt 
              /Fo...\target\nar\obj\amd64-Windows-msvc\ComplexLineCommentTokenManager.1e3a03c3.obj 
              ../../target/generated-sources/cpp/ComplexLineCommentTokenManager.cc -->
              <commandLogLevel>2</commandLogLevel>
              <windowsMsvcVersion>${env.VISUALSTUDIOVERSION}</windowsMsvcVersion>
              <!--              <windowsMsvcVersion>17.10</windowsMsvcVersion>-->
              <windowsMsvcDir>${env.VISUALSTUDIODIR}</windowsMsvcDir>
              <!--              <windowsMsvcDir>C:/Progra~1/MIB055~1/2022/PROFES~1/</windowsMsvcDir>-->
              <!--              <maxCores>1</maxCores>-->
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <!--  just as a record of a less usable solution for above -->
    <!--  <properties>-->
    <!--    <nar.windows.msvc.version>17.10</nar.windows.msvc.dir>-->
    <!--    <nar.windows.msvc.dir>C:/Progra~1/MIB055~1/2022/PROFES~1/</nar.windows.msvc.dir>-->
    <!--  </properties>-->

    <profile>
      <!-- windows-debug manual (uncomment/comment) profile needed to enable nar-vcproj (to produce
            the VisualStudio 2005 project file - which will be modified by later versions of VS) -->
      <!--      <id>windows-debug</id>-->
      <activation>
        <property>
          <name>env.VISUALSTUDIOVERSION</name>
        </property>
      </activation>
    </profile>

    <profile>
      <!-- requested by nar-maven-plugin for the goal nar:nar-vcproj
           if one wants to generate the MSVC project-->
      <id>windows-debug</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.maven-nar</groupId>
            <artifactId>nar-maven-plugin</artifactId>
            <configuration>
              <cpp>
                <includePaths>
                  <includePath>
                    <path>${project.basedir}/src/main/cpp</path>
                  </includePath>
                  <includePath>
                    <path>${project.basedir}/target/generated-sources/cpp</path>
                  </includePath>
<!--                  <includePath>-->
<!--                    <path>${project.basedir}/target/generated-sources/jjtree</path>-->
<!--                  </includePath>-->
                </includePaths>
              </cpp>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>

  </profiles>
</project>