/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
options {
  STATIC = false; // not JavaCC's default; will not change much in C++
  // for ofstream
  PARSER_INCLUDE = "<fstream>"; 
}

PARSER_BEGIN(Digest)

private:
  int count = 0;
  std::ofstream *digpw;

public:
  void setDigpw(std::ofstream *aDigpw) {
    digpw = aDigpw;
  }

PARSER_END(Digest)

JJString MailFile() :
{ JJString mail, mails = ""; }
{
  (
    { count++; }
    mail = MailMessage()
    {
      mails += mail;
      std::cout << count << "-";
      std::cout.flush();
    }
  )*
  <EOF>
  {
    std::cout << std::endl;
    return mails;
  }
}

JJString MailMessage() :
{
  Token *subj, *from, *date,* body;
  subj = nullptr;
  from = nullptr;
  date = nullptr;
  JJString buffer = "";
}
{
  ( subj = <SUBJECT> | from = <FROM> | date = <DATE> )+
  {
    *digpw << count << ". " <<  (subj == nullptr ? "no subject" : subj->image()) << std::endl;
    buffer += "\n";
    buffer += "Message " + std::to_string(count) + ":\n";
    buffer += "\n";
    buffer += "Subject: " + (subj == nullptr ? "no subject" : subj->image()) + "\n";
    buffer += "From: " + (from == nullptr ? "" : from->image()) + "\n";
    buffer += "Date: " + (date == nullptr ? "" : date->image()) + "\n";
    buffer += "\n";
  }
  (
    body = <BODY>
    {
      buffer += body->image();
    }
  )*
  <END>
  {
    buffer += "\n";
    buffer += "----------------------------------------------------------------------\n";
    return buffer;
  }
}

TOKEN :
{
  < #EOL : "\n" | "\r" | "\r\n" >
|
  < #TWOEOLS : ( ( "\n" | "\r\n" ) <EOL>) | ( "\r\r" [ "\n" ] )>
|
  < #NOT_EOL : ~[ "\n", "\r" ] >
}

<DEFAULT>
SKIP :
{
  < <EOL> "*** EOOH ***" <EOL> > : MAILHEADER
|
  <~[]>
}

<MAILHEADER>
SKIP :
{
  < _TWOEOLS : <TWOEOLS> > : MAILBODY
    // We cannot have just a reference to a regular expression in a
    // lexical specification - i.e., we cannot simply have <TWOEOLS>.
|
  "Subject: " : MAILSUBJECT
|
  "From: " : MAILFROM
|
  "Date: " : MAILDATE
|
  <~[]>
}

<MAILSUBJECT>
TOKEN :
{
  < SUBJECT : ( <NOT_EOL> )+ >
}

<MAILSUBJECT>
SKIP :
{
  < _EOL1 : <EOL> > : MAILHEADER
}

<MAILFROM>
TOKEN :
{
  < FROM : ( <NOT_EOL> )+ >
}

<MAILFROM>
SKIP:
{
  < _EOL2 : <EOL> > : MAILHEADER
}

<MAILDATE>
TOKEN:
{
  < DATE : ( <NOT_EOL> )+ >
}

<MAILDATE>
SKIP :
{
  < _EOL3 : <EOL> > : MAILHEADER
}

<MAILBODY>
TOKEN :
{
  < BODY : ( ~["\n", "\r", "\u001f" ] )* <EOL> >
| 
  < END : "\u001f" > : DEFAULT
}
