/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
options {
  STATIC = true; // JavaCC's default
  // for decl of FaqMain.fix(); contains 'include JavaCC.h' & 'using namespace std'
  PARSER_INCLUDE = "FaqMain.h"; 
}

PARSER_BEGIN(Faq)

public:
  int count = 0;
  int beginAt;
  JJString outdir;
  ofstream *indexpw;

// care: the line package, even if in comment, will be used!
/*
pac-kage faq; // different from Digest, to allow different helper files

import java.io.*;

public class Faq {
  static int count = FaqMain.count;
  static int beginAt = FaqMain.beginAt;
  static String outdir = FaqMain.outdir;
  static PrintWriter indexpw = FaqMain.indexpw;
}
*/

PARSER_END(Faq)

void MailFile() :
{}
{
  (
    { count++; }
    MailMessage()
    {
      cout << (count + ".");
      cout.flush();
    }
  )*
  <EOF>
  {
    cout << endl;
    indexpw->close();
  }
}

void MailMessage() :
{
  ofstream msgpw;
  Token *subj, *from, *date, *body;
  subj = nullptr;
  from = nullptr;
  date = nullptr;
  if (count >= beginAt) {
    msgpw.open(to_string(count) + ".html");
    if (!msgpw.is_open()) {
      cerr << "Cannot open output file " << count << ".html" << endl;
      exit(4);
    }
  } else {
    cerr << "count (" << count << ") < beginAt (" << beginAt << ")" << endl;
    return;
  }
}
{
  ( subj = <SUBJECT> | from = <FROM> | date = <DATE> )+
  {
    *indexpw << "<a href=\"" << count << ".html\">";
    if (subj == nullptr) {
      *indexpw << "no subject</a><br>" << endl;
    } else {
      *indexpw << FaqMain::fix(subj->image()) << "</a><br>" << endl;
    }
    if (count >= beginAt) {
      msgpw << "<title>" + (subj == nullptr ? "no subject" : FaqMain::fix(subj->image())) + "</title>" << endl;
      msgpw << "Subject: " + (subj == nullptr ? "no subject" : FaqMain::fix(subj->image())) + "<br>" << endl;
      msgpw << "From: " + (from == nullptr ? "" : FaqMain::fix(from->image())) + "<br>" << endl;
      msgpw << "Date: " + (date == nullptr ? "" : FaqMain::fix(date->image())) + "<br>" << endl;
      msgpw << "<br>" << endl;
    }
  }
  (
    body = <BODY>
    {
      if (count >= beginAt) {
        msgpw << (FaqMain::fix(body->image()) + "<br>");
      }
    }
  )*
  <END>
  {
    if (msgpw) {
      msgpw.close();
    }
  }
}

TOKEN:
{
  <#EOL: "\n" | "\r" | "\r\n">
|
  <#TWOEOLS: ( ( "\n" | "\r\n" ) <EOL>) | ( "\r\r" [ "\n" ] )>
|
  <#NOT_EOL: ~[ "\n", "\r" ]>
}

<DEFAULT>
SKIP :
{
  < <EOL> "*** EOOH ***" <EOL> > : MAILHEADER
|
  <~[]>
}

<MAILHEADER>
SKIP :
{
  < _TWOEOLS : <TWOEOLS> > : MAILBODY
    // We cannot have just a reference to a regular expression in a
    // lexical specification - i.e., we cannot simply have <TWOEOLS>.
|
  "Subject: " : MAILSUBJECT
|
  "From: " : MAILFROM
|
  "Date: " : MAILDATE
|
  <~[]>
}

<MAILSUBJECT>
TOKEN :
{
  < SUBJECT : ( <NOT_EOL> )+ >
}

<MAILSUBJECT>
SKIP :
{
  < _EOL1 : <EOL> > : MAILHEADER
}

<MAILFROM>
TOKEN :
{
  < FROM : ( <NOT_EOL> )+ >
}

<MAILFROM>
SKIP:
{
  < _EOL2 : <EOL> > : MAILHEADER
}

<MAILDATE>
TOKEN:
{
  < DATE : ( <NOT_EOL> )+ >
}

<MAILDATE>
SKIP :
{
  < _EOL3 : <EOL> > : MAILHEADER
}

<MAILBODY>
TOKEN :
{
  < BODY : ( ~["\n", "\r", "\u001f" ] )* <EOL> >
| 
  < END : "\u001f" > : DEFAULT
}
