options {
  DEBUG_TOKEN_MANAGER=true;
  JAVA_UNICODE_ESCAPE = true; // (JavaCC - default false)
//  KEEP_LINE_COLUMN = false; // (JavaCC - default true; undocumented) // test
}

PARSER_BEGIN(ComplexLineComment)

PARSER_END(ComplexLineComment)

SKIP : { " " | "\t" | "\n" | "\r" }

TOKEN :
{
   <#NA : ~[ "-", "\r", "\n" ] >
| <#EOL : ( "\n" | "\r" | "\r\n" ) >
}

SPECIAL_TOKEN :
{
  "--" : LineComment
}

< LineComment >
SPECIAL_TOKEN :
{
  < (
      < NA >
    | "-" < NA >
    )*
    (
      < EOL >
    | "-" < EOL >
    | "-" "-"
    )? > : DEFAULT
}

TOKEN :
{
  < Id : [ "a"-"z", "A"-"Z" ] ( [ "a"-"z", "A"-"Z", "0"-"9", "-" ] )* >
  { std::cout << matchedToken->toString() << std::endl; }
}

void Input() :
{}
{
  ( <Id> )*
  // { std::cout << "Finished ID+" << std::endl; std::cerr << System.err.println("Finished ID+" << std::endl; }
  <EOF>
  // { std::cout << "EOF found"    << std::endl; std::cerr << System.err.println("EOF found"    << std::endl; }
}
