options {
  DEBUG_TOKEN_MANAGER=true;
  TOKEN_MANAGER_INCLUDE="MyTM.h"; 
}

PARSER_BEGIN(ComplexLineComment)

PARSER_END(ComplexLineComment)

TOKEN_MGR_DECLS : {
  
  int myfield;
  
  void mymethod() {
    std::cout << "coucou from tm" << std::endl; 
    return;
  };
  
}


SKIP : { " " | "\t" | "\n" | "\r" }

TOKEN :
{
   <#NA : ~[ "-", "\r", "\n" ] >
| <#EOL : ( "\n" | "\r" | "\r\n" ) >
}

SPECIAL_TOKEN :
{
  "--" : LineComment
}

< LineComment >
SPECIAL_TOKEN :
{
  < (
      < NA >
    | "-" < NA >
    )*
    (
      < EOL >
    | "-" < EOL >
    | "-" "-"
    )? > : DEFAULT
}

TOKEN :
{
  < Id : [ "a"-"z", "A"-"Z" ] ( [ "a"-"z", "A"-"Z", "0"-"9", "-" ] )* >
  { std::cout << matchedToken->toString() << std::endl; }
}

void Input() :
{}
{
  ( <Id> )*
  // { std::cout << "Finished ID+" << std::endl; std::cerr << System.err.println("Finished ID+" << std::endl; }
  <EOF>
  // { std::cout << "EOF found"    << std::endl; std::cerr << System.err.println("EOF found"    << std::endl; }
}
